name       : toxcore
version    : 3767
release    : 8
source     :
    - http://stroblindustries.com/solus-tarballs/toxcore-3767.tar.xz : 9b229df95371815b3bd6e3a6cecc460b6c1cc570ab1bb04a44452a15233c6f1c
license    : GPL-3.0
component  : security.library
summary    : toxcore is the core library for Tox communication clients.
description: |
    toxcore is the core library for Tox communication clients.
builddeps  :
    - pkgconfig(libconfig)
    - pkgconfig(libsodium)
    - pkgconfig(opus)
    - pkgconfig(vpx)
libsplit   : no
setup      : |
    %reconfigure --disable-static --enable-daemon
build      : |
    %make
install    : |
    %make_install
