name       : toxcore
version    : 0.1.7
release    : 10
source     :
    - https://github.com/TokTok/c-toxcore/archive/v0.1.7.tar.gz : 8053e246344b1700cc9ee65fe8921ea97db999767e669d76298eca3a4f88c53d
license    : GPL-3.0
component  : security.library
summary    : toxcore is the core library for Tox communication clients.
description: |
    toxcore is the core library for Tox communication clients.
builddeps  :
    - pkgconfig(libconfig)
    - pkgconfig(libsodium)
    - pkgconfig(opus)
    - pkgconfig(vpx)
libsplit   : no
setup      : |
    %reconfigure --disable-static --enable-daemon
build      : |
    %make
install    : |
    %make_install
