name       : toxcore
version    : 0.1.6
release    : 9
source     :
    - https://github.com/TokTok/c-toxcore/releases/download/v0.1.6/c-toxcore-v0.1.6.tar.lz : c51dfaf30cddbfb9a6080c8202d68113452224570109cd9a6f1b7d9709eae6af
license    : GPL-3.0
component  : security.library
summary    : toxcore is the core library for Tox communication clients.
description: |
    toxcore is the core library for Tox communication clients.
builddeps  :
    - pkgconfig(libconfig)
    - pkgconfig(libsodium)
    - pkgconfig(opus)
    - pkgconfig(vpx)
libsplit   : no
setup      : |
    %reconfigure --disable-static --enable-daemon
build      : |
    %make
install    : |
    %make_install
