name       : toxcore
version    : 0.2.4
release    : 19
source     :
    - https://github.com/TokTok/c-toxcore/archive/v0.2.4.tar.gz : f4c712a8a4b0653ae42b472b4a2a2c969c21e6959a07fc32b302b97480ffba69
license    : GPL-3.0-or-later
component  : security.library
summary    : toxcore is the core library for Tox communication clients.
description: |
    Tox is a peer to peer (serverless) instant messenger aimed at making security and privacy easy to obtain for regular users. It uses NaCl for its encryption and authentication.
libsplit   : no
builddeps  :
    - pkgconfig(libconfig)
    - pkgconfig(libsodium)
    - pkgconfig(opus)
    - pkgconfig(vpx)
setup      : |
    %cmake -DENABLE_STATIC=OFF .
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/tox-bootstrapd.service $installdir/%libdir%/systemd/system/tox-bootstrapd.service
    install -Dm00644 $pkgfiles/tox-bootstrapd.conf $installdir/etc/tox-bootstrapd.conf
    install -Dm00644 $pkgfiles/tox-bootstrapd.sysusers $installdir/%libdir%/sysusers.d/tox-bootstrapd.conf
    install -Dm00644 $pkgfiles/toxcore.tmpfiles $installdir/%libdir%/tmpfiles.d/tox-bootstrapd.conf
