name       : toxcore
version    : 0.2.11
release    : 22
source     :
    - https://github.com/TokTok/c-toxcore/archive/v0.2.11.tar.gz : f111285b036d7746ce8d1321cf0b89ec93b4fad8ae90767a24e50230bbee27e1
license    : GPL-3.0-or-later
component  : security.library
summary    : toxcore is the core library for Tox communication clients.
description: |
    Tox is a peer to peer (serverless) instant messenger aimed at making security and privacy easy to obtain for regular users. It uses NaCl for its encryption and authentication.
libsplit   : no
builddeps  :
    - pkgconfig(libconfig)
    - pkgconfig(libsodium)
    - pkgconfig(opus)
    - pkgconfig(vpx)
setup      : |
    %cmake -DENABLE_STATIC=OFF .
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/tox-bootstrapd.service $installdir/%libdir%/systemd/system/tox-bootstrapd.service
    install -Dm00644 $pkgfiles/tox-bootstrapd.conf $installdir/etc/tox-bootstrapd.conf
    install -Dm00644 $pkgfiles/tox-bootstrapd.sysusers $installdir/%libdir%/sysusers.d/tox-bootstrapd.conf
    install -Dm00644 $pkgfiles/toxcore.tmpfiles $installdir/%libdir%/tmpfiles.d/tox-bootstrapd.conf
